### ISSUE TITLE
[Question] Why did you take the approach you did?

### ISSUE THREAD

**Issue by smiller171** [hverr/go-redirect#3]
Why did you take this particular approach with the redirects? Wouldn't a 301 redirect be a better solution? Is it that much harder to implement?

**Comment by hverr** [comment]
This is being used in an experimental setup, and we did not want the browser to cache the redirects. In a production environment a 301 would indeed be better.

Furthermore, when looking at some big companies, 301's and 302's are being used interchangeably.
- Google uses 302
- Facebook uses 302
- Yahoo uses 301
- GitHub uses 301

---

Changing from 302 to 301 would only require a change in [this line](https://github.com/hverr/go-redirect/blob/e88610df8ebdd990e1176eedcaa7782c95e5655e/main.go#L53).

**Comment by smiller171** [comment]
I'm pretty new to Go, but I knew it was the solution I wanted for the smallest possible Docker container. Unfortunately I don't understand the code well at all. Is it the `http.StatusFound` that would need to be changed? You can see the changes I made around Docker in my fork.

**Comment by hverr** [comment]
Yes, you'd need to change`http.StatusFound` to `http.StatusMovedPermanently`. If you'd reopen your pull request, I'd be happy to take a look and maybe merge your changes.

**Comment by smiller171** [comment]
I didn't even mean to open those PRs. I was merging my own feature branches in and forgot to change the HEAD fork. That said I'll submit a PR if you want to take a look.
