### ISSUE TITLE
This is very awesome! And so simple.

### ISSUE THREAD

**Issue by nogweii** [hverr/go-redirect#6]
First off, thanks for writing this. I had the same idea, and was about to write it myself when I decided to look around github first.

Secondly, because this was so simple, I used it as a test to learn systemd's sandboxing capabilities, and I've gotten it pretty locked down. Here is my unit file for reference:

```
[Unit]
Description=HTTP to HTTPS redirect
Documentation=https://github.com/hverr/go-redirect
After=network.target

[Service]
ExecStart=/usr/local/bin/go-redirect
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
RestrictAddressFamilies=AF_INET AF_INET6
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
```

I can lock it down even more so if I strace the binary, for example, but I think this would be a very secure thing. Not that I can imagine much opportunity for a hacker to break this, but it was a fun distraction for an hour. :)

**Comment by hverr** [comment]
Thank you for your comment. I'm glad this utility application was useful to you. If you want you can send me a pull request with your unit file. I'll be happy to test and merge it.
